name: Deploy MobileProducerAPI

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Use the correct action for Docker login
        with:
          username: planetsystems  # Your Docker Hub username
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Your Docker token secret

      - name: Build and push Docker image
        run: |
          docker build -t planetsystems/mobile-producer-api:${{ github.sha }} .
          docker push planetsystems/mobile-producer-api:${{ github.sha }}
