name: Deploy MobileProducerAPI

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" 

      
      - name: Build and push Docker image
        run: |
          docker build -t planetsystems/mobile-producer-api:${{ github.sha }} .
          docker push planetsystems/mobile-producer-api:${{ github.sha }}
